on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - dev
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: docker://zoro2001411/pr-agent:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROQ_KEY: ${{ secrets.GROQ_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}